# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        # password = admin
                        password: $2y$13$nEScVrvxLrhruPnyC5ZYr.IotRyae.Iv2tZtfoeXnslda9Uu.39Qi
                        roles: 'ROLE_ADMIN'
                    bob:
                        # password = testpass
                        password: $2y$13$2f1m7cBKaMllfHPLOHW6X.1VtnNf8ZtnaGPshlVbnrTiSGdudICy6
                    dave:
                        # password = davepass
                        password: $2y$13$.ueuTRhPEf8TFEpHKIWM5ezK1fPpZtoLoBNzAZcZCyjIuxAWNrwVO

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }